CREATE TABLE users
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL      VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD   VARCHAR(255),
    NAME       VARCHAR(255),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);
